CREATE TABLE users(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    name text DEFAULT '',
    avatar varchar DEFAULT '',
    email varchar DEFAULT '',
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);