CREATE TABLE users(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    name varchar(80) not NULL,
    avatar varchar(300) not NULL,
    email varchar(254) not NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);


-- char[acter] -> N Caracteres
-- Exemplos:
--   char(1) -> "n"
--   char(5) -> "n    "
-- Casos de uso:
--   Códigos fixos (ex: "A", "B", "C")
--   Siglas (ex: "SP", "RJ", "MG")

-- varchar -> De 0 até N Caracteres
-- Exemplos:
--   varchar(1) -> "n"
--   varchar(5) -> "n", "na", "nat", "nath"
-- Casos de uso:
--   Nomes, sobrenomes, endereços, etc...

-- text -> De 0 até ????? Caracteres
-- Exemplos:
--   text -> "n", "na", "nat", "nath", etc...
-- Casos de uso:
--   Descrições, biografias, comentários, código, etc...